main: fr.bobsmil3y.gamerulemanager.Main
name: Gamerule-Manager
version: 1.0.0
author: BoBsmil3Y
description: A plugin to show and manage easily your world gamerule.
api: 1.15.2
commands:
  gmanager:
    description: Use to manage you gamerule world.
    permission: gamerulemanager.admin